#!/bin/sh

bspc config border_width 3
bspc config top_padding 0
bspc config window_gap 6
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
#bspc config focus_by_distance true
#bspc config auto_cancel true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc desktop --layout monocle

bspc config focused_border_color \#2379E2
bspc config normal_border_color none
bspc config presel_border_color none

#bspc rule -a Chrome fullscreen=on center=on desktop='^1'
#bspc rule -a urxvt fullscreen=on center=on desktop='^2'
#bspc rule -a mpv state=floating center=on desktop='^3'

sxhkd &
urxvt -e tmux -2 new-session -A -s local
